/* ZIP store writer. UTF-8 names; no compression, dependencies, or remote calls. */
(function(root){'use strict';
const enc=new TextEncoder();const table=Array.from({length:256},(_,n)=>{let c=n;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function concat(chunks){const b=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let p=0;for(const c of chunks){b.set(c,p);p+=c.length;}return b;}
function header(size){const b=new Uint8Array(size);return[b,new DataView(b.buffer)];}
function zip(entries){const locals=[],centrals=[];let offset=0;for(const e of entries){const name=enc.encode(e.name);const data=typeof e.text==='string'?enc.encode(e.text):e.data;const crc=crc32(data);const [l,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);locals.push(l,name,data);const[c,w]=header(46);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint16(14,33,true);w.setUint32(16,crc,true);w.setUint32(20,data.length,true);w.setUint32(24,data.length,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);centrals.push(c,name);offset+=l.length+name.length+data.length;}const central=concat(centrals);const[end,v]=header(22);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,central.length,true);v.setUint32(16,offset,true);return concat([...locals,central,end]);}
root.AIAZip={zip,crc32};if(typeof module!=='undefined')module.exports=root.AIAZip;
})(typeof window!=='undefined'?window:globalThis);
